demo/index.html

Adding cosmoz-omnitable name attribute to demo

---

cosmoz-omnitable-treenode-column.html

Handle non Array or null, undefined in `_computeHideFromRoot` reduce result.

Handle non Array in _computeHideFromRoot

---

bower.json
cosmoz-omnitable-treenode-column.html
test/.eslintrc.json
test/basic.html
test/index.html

Readonly Test and SuggestionList observe ownerTree.

Add tests and observe ownerTree when computing suggestion list

---

cosmoz-omnitable-treenode-column.html

Values must be a non empty array in `_computeSuggestionList`

Values must be a non empty array in _computeSuggestionList

---

cosmoz-omnitable-treenode-column.html

Add default minWidth
depends on Neovici/cosmoz-omnitable#144

Add default minWidth

---

.codeclimate.yml
.eslintignore
.gitignore
.travis.yml
bower.json
package.json
wct.conf.json
yarn.lock

fixes https://github.com/Neovici/cosmoz-omnitable-treenode-column/issues/19

Tests code coverage

---

.eslintignore
.gitignore
.travis.yml
analysis.json
bower.json
cosmoz-omnitable-treenode-column.html
demo/index.html
package.json
test/basic.html
yarn.lock

fixes https://github.com/Neovici/cosmoz-omnitable-treenode-column/issues/17

Polymer 2 update and variants in bower.json

---

bower.json
test/basic.html
yarn.lock

Implemented simple Test for https://github.com/Neovici/cosmoz-omnitable-treenode-column/issues/21
Updated dependency paper-autocomplete version from 3.6.0 to 3.7.0
Tests passed on localhost.  
fixes #24

When source changed update suggestions list.

---

cosmoz-omnitable-treenode-column.html

Undefined check in _computeHideFromRoot

---

cosmoz-omnitable-treenode-column.html

Bugfix, _computeHideFromRoot failed on undefined paths, replacing some undefined with null, adding documentation.
Redmine issue is #19676.

Bugfix, _computeHideFromRoot failed on undefined paths

---

.travis.yml
bower.json
cosmoz-omnitable-treenode-column.html
package-lock.json
package.json
yarn.lock

Upgrade to use OmnitableColumnMixin

---

cosmoz-omnitable-treenode-column.html

`<dom-module>` is pointless considering that the element uses static get template()

(patch) remove use of <dom-module>

---

cosmoz-omnitable-treenode-column.html

Fixes Neovici/cosmoz-omnitable#201

(patch) Folded columns/values styling

---

cosmoz-omnitable-treenode-column.js
package-lock.json
package.json

Avoid acting on undefined.
Should fix https://github.com/Neovici/cosmoz-frontend/issues/1555
Also upgrade deps.
Signed-off-by: Patrik Kullman <patrik.kullman@neovici.se>

Tooltip: Highlight and check deps

---

cosmoz-omnitable-treenode-column.js

Re https://github.com/Neovici/cosmoz-frontend/pull/1611

fix: error when ownerTree is undefined

---

.eslintignore
cosmoz-omnitable-treenode-column.js

Fixes filter and switches chip position

fix: fixes filter and ui

---

package-lock.json
package.json

This column is compatible with both omnitable v5 and v6.

fix: upgrade to omnitable v6

---

.github/workflows/ci.yml
.vscode/settings.json
cosmoz-omnitable-treenode-column-input.js
cosmoz-omnitable-treenode-column.js
package-lock.json
package.json
stories/cosmoz-omnitable-treenode-column.stories.js
test/cosmoz-omnitable-treenode-column.test.js
utils.js

BREAKING CHANGE: the column uses the updated omnitable column API

feat!: upgrade to omnitable v8

---

cosmoz-omnitable-treenode-column-input.js
cosmoz-omnitable-treenode-column.js
package-lock.json
package.json

Fixed bug caught by acceptance tests.

fix: integration with omnitable search helper and useOTS

---

package-lock.json
package.json

feat(deps): update cosmoz-autocomplete

---

package-lock.json
package.json

BREAKING CHANGE: Upgrade to lit@^2 and haunted@^5

feat: upgrade to lit@^2

---

cosmoz-omnitable-treenode-column.js
package-lock.json
package.json

fix: restore query notification

---

package-lock.json
package.json
utils.js

[Dev Story 9302](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/9302/)
There was one last refactor to do in this folder as well. The import path for memoize functions is updated.

AB9302 - memoize refactor

---

cosmoz-omnitable-treenode-column.js
package-lock.json
package.json
test/cosmoz-omnitable-treenode-column.test.js
utils.js

As we discussed the default behavior will be to be able to select several values. 
An small change is needed in omnitable to pass along the three new values. I will create an PR for that.

Adding support for filtering on several nodes

---

cosmoz-omnitable-treenode-column.js
package-lock.json

Fix for what we discussed in FE issue 5085

fix(limit,hideFromRoot,showMaxNodes): properties were not set

---

.github/workflows/ci.yml
cosmoz-omnitable-treenode-column.js
package-lock.json
package.json

feat: allow autocomplete v6

---

package-lock.json
package.json

feat: update autocomplete

---

.husky/commit-msg
cosmoz-omnitable-treenode-column.js
package-lock.json
package.json

Implement `values` fn for the autocomplete in treenode column.

feat: implement values fn

---

.eslintignore
.prettierrc
.storybook/main.js
eslint.config.mjs
package-lock.json
package.json
test/cosmoz-omnitable-treenode-column.test.js

BREAKING CHANGE: Update cosmoz-dropdown

feat: update cosmoz-dropdown
